"""Validate translation sources and generate the standalone card (Python 3.10+)."""
from pathlib import Path
import argparse
import json
import re

ROOT = Path(__file__).resolve().parents[1]
MARKER = '/* __EMBY_TRANSLATIONS__ */'


def unique_keys(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f'Duplicate translation key: {key}')
        result[key] = value
    return result


def load_translations(folder):
    dictionaries = {}
    for file in sorted(folder.glob('*.json')):
        if not re.fullmatch(r'[a-z]{2,3}(?:-[a-z0-9]{2,8})*', file.stem):
            raise ValueError(f'Invalid language filename: {file.name}; use lowercase language tags')
        data = json.loads(file.read_text(encoding='utf-8'), object_pairs_hook=unique_keys)
        if not isinstance(data, dict) or not data:
            raise ValueError(f'{file.name}: expected a nonempty object')
        if any(not isinstance(value, str) or not value.strip() for value in data.values()):
            raise ValueError(f'{file.name}: all translations must be nonempty strings')
        dictionaries[file.stem] = data
    if 'en' not in dictionaries:
        raise ValueError('The English reference file en.json is required')
    reference = dictionaries['en']
    for language, data in dictionaries.items():
        extra = data.keys() - reference.keys()
        if extra:
            raise ValueError(f'{language}: unknown translation keys: {sorted(extra)}')
        missing = reference.keys() - data.keys()
        if missing:
            print(f'{language}: English fallback for {sorted(missing)}')
        for key, value in data.items():
            if sorted(re.findall(r'\{\w+\}', value)) != sorted(re.findall(r'\{\w+\}', reference[key])):
                raise ValueError(f'{language}.{key}: placeholders must match English')
    return dictionaries


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if the generated JS is out of date; do not write files')
    args = parser.parse_args()
    dictionaries = load_translations(ROOT/'frontend/translations')
    source = (ROOT/'frontend/emby-metadata-card.js').read_text(encoding='utf-8')
    if source.count(MARKER) != 1:
        raise ValueError('Expected exactly one translation marker in the card source')
    result = '// Generated by scripts/build_card.py. Edit frontend sources instead.\n' + source.replace(MARKER, json.dumps(dictionaries, ensure_ascii=False, indent=2))
    output = ROOT/'custom_components/emby_metadata/static/emby-metadata-card.js'
    if args.check:
        if not output.exists() or output.read_text(encoding='utf-8') != result:
            raise SystemExit('Generated card is out of date. Run python scripts/build_card.py')
        print('Translations valid; generated card is up to date.')
    else:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(result, encoding='utf-8', newline='\n')
        print('Generated card with languages: ' + ', '.join(dictionaries))


if __name__ == '__main__':
    main()
